---
- hosts:  myWebServers
  become: yes
  gather_facts: yes
  tasks:  
  - name: Installing Apache2 on Ubuntu
    apt:
      name: mywebpackonUbuntu
      state:  present
    when: ansible_os_family=="Debian"